spring:
  servlet:
    multipart:
      max-request-size: 100MB
      maxFileSize: 10MB
      #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.241:3306/server_manager?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:   #静态文件
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss